truncate vk.`user_like`;
truncate vk.`post`;
truncate vk.`message`;
truncate vk.`friend_request`;
truncate vk.`user_community`;
truncate vk.`profile`;
DELETE FROM vk.`content`;
DELETE FROM vk.`content_type`;
DELETE FROM vk.`media`;
DELETE FROM vk.`media_type`;
DELETE FROM vk.`community`;
DELETE FROM vk.`user`;
